# /services/version_control.py

from typing import List, Dict, Any
from datetime import datetime

def _index_flows(flows: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """
    Indexes a list of flows into a dictionary mapped by their unique API ID.
    This provides perfect 1-to-1 tracking of individual contracts/grants.
    
    CRITICAL FIX: If a record lacks a stable ID (or uses an unstable Python hash),
    we create a deterministic 'AGG_' (Aggregate) signature WITHOUT the amount.
    We then SUM the amounts of colliding records to prevent 100% false-positive 
    volatility triggered by Python hash seed restarts or modified dollar values.
    """
    indexed = {}
    
    for f in flows:
        # Use the precise ID from the USAspending API as the absolute anchor
        sig = str(f.get('source_record_id', 'UNKNOWN_ID'))
        
        # Intercept legacy missing IDs and the unstable random hashes generated by data_engine.py
        if not sig or sig == "UNKNOWN_ID" or sig.startswith("FALLBACK_"):
            # Create a stable, deterministic signature WITHOUT the amount.
            sig = f"AGG_{f.get('year')}|{f.get('source_database')}|{f.get('layer')}|{f.get('agency')}|{f.get('recipient')}"
            
        if sig not in indexed:
            indexed[sig] = f.copy()
            # Ensure the amount is a float so we can safely do math on it if collisions occur
            indexed[sig]['amount_usd'] = float(f.get('amount_usd', 0))
        else:
            # If there's a collision (either legitimate ID collision or an AGG_ fallback bucket),
            # we MUST safely sum the amounts so no money is lost in the Watchdog calculation.
            current_amount = float(indexed[sig].get('amount_usd', 0))
            new_amount = float(f.get('amount_usd', 0))
            indexed[sig]['amount_usd'] = current_amount + new_amount
                
    return indexed


def _calculate_impact(delta_usd: float, delta_percent: float) -> str:
    """Categorizes the severity of the revision based on thresholds."""
    abs_usd = abs(delta_usd)
    abs_pct = abs(delta_percent)
    
    if abs_usd > 1_000_000 or abs_pct > 30.0:
        return "HIGH"
    if abs_usd > 250_000 or abs_pct > 15.0:
        return "MEDIUM"
    return "LOW"


def compare_ledgers(local_flows: List[Dict[str, Any]], live_flows: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    The Git-style Diff Engine. Enhanced for Watchdog Mode.
    Compares local offline data against live API data to detect Added, Removed, and Modified federal flows.
    """
    
    # 1. Index both datasets to ensure a clean 1-to-1 record comparison
    local_idx = _index_flows(local_flows)
    live_idx = _index_flows(live_flows)
    
    current_year = datetime.now().year
    
    diff_results = {
        "added": [],
        "removed": [],
        "modified": [],
        "unchanged": [],
        "totals": {
            "local_volume": sum(float(f['amount_usd']) for f in local_idx.values()),
            "live_volume": sum(float(f['amount_usd']) for f in live_idx.values()),
            "net_change": 0.0
        }
    }
    
    # Calculate global net change
    diff_results["totals"]["net_change"] = diff_results["totals"]["live_volume"] - diff_results["totals"]["local_volume"]

    # 2. Scan the Live API data to find Additions and Modifications
    for key, live_flow in live_idx.items():
        flow_year = live_flow.get("year", current_year)
        is_retroactive = flow_year < current_year
        
        if key in local_idx:
            local_amount = float(local_idx[key]["amount_usd"])
            live_amount = float(live_flow["amount_usd"])
            delta = live_amount - local_amount
            
            # Allow a small float tolerance for rounding errors (e.g., $1.00)
            if abs(delta) > 1.0:
                delta_percent = (delta / abs(local_amount)) * 100 if local_amount != 0 else 100.0
                impact = _calculate_impact(delta, delta_percent)
                
                diff_results["modified"].append({
                    **live_flow,
                    "old_amount": local_amount,
                    "new_amount": live_amount,
                    "delta": delta,
                    "delta_percent": delta_percent,
                    "is_retroactive": is_retroactive,
                    "impact_level": impact,
                    "change_type": "MODIFIED"
                })
            else:
                diff_results["unchanged"].append(live_flow)
                
            # Remove from local dictionary so we can track what's left over
            del local_idx[key]
        else:
            # It's in the Live API but wasn't in our Local DB!
            live_amount = float(live_flow["amount_usd"])
            impact = _calculate_impact(live_amount, 100.0)
            diff_results["added"].append({
                **live_flow,
                "old_amount": 0.0,
                "new_amount": live_amount,
                "delta": live_amount,
                "delta_percent": 100.0,
                "is_retroactive": is_retroactive,
                "impact_level": impact,
                "change_type": "ADDED"
            })

    # 3. Anything left in the Local DB was NOT in the Live API (Redacted/Removed)
    for key, local_flow in local_idx.items():
        flow_year = local_flow.get("year", current_year)
        is_retroactive = flow_year < current_year
        local_amount = float(local_flow["amount_usd"])
        delta = -local_amount
        impact = _calculate_impact(delta, -100.0)
        
        diff_results["removed"].append({
            **local_flow,
            "old_amount": local_amount,
            "new_amount": 0.0,
            "delta": delta,
            "delta_percent": -100.0,
            "is_retroactive": is_retroactive,
            "impact_level": impact,
            "change_type": "REMOVED"
        })

    # 4. Sort the lists by the absolute size of the change (biggest impacts first)
    diff_results["added"] = sorted(diff_results["added"], key=lambda x: x["delta"], reverse=True)
    diff_results["removed"] = sorted(diff_results["removed"], key=lambda x: abs(x["delta"]), reverse=True)
    diff_results["modified"] = sorted(diff_results["modified"], key=lambda x: abs(x["delta"]), reverse=True)
    
    return diff_results